### ISSUE TITLE
No data shown

### ISSUE THREAD

**Issue by Richard238** [daterrell/MMM-ISS#3]
Further to msg below,  I did a MM restart, now MMM-ISS shows nothing, just the blank as described below for a fraction of a second, then nothing at all. 
Hope you can help,
Thank you.

Hi, I just installed this, but MM just shows

Next ISS Fly-Over:
Visible    Max Height
Appears    Disappears 

Why do I get no time, date, location data? (location left at default to test)
Here's how I've added it to config.js

`		{
		    module: 'MMM-ISS',
		    position: 'bottom_right',
		    config: {
		    // These values must come from available locations on the SpotTheStation site: https://spotthestation.nasa.gov/
			country: "United States",
			region: "Massachusetts",
			city: "Boston"
			    }
		},`

**Comment by daterrell** [comment]
2 parts:
- The module gets added on startup, so it's shown by default with no data.  I probably could make it hidden, but it wasn't a big enough problem at least for me.
- It eventually disappears because it got the data from NASA, and there aren't any upcoming ISS fly-overs for the chosen location.

So that's why you see it for a moment (as empty) and then it disappears.  The module is only shown when there's a fly-over that you're likely to see (is at a time of day where it's dark enough, and it will go high enough in the sky).
