### ISSUE TITLE
No data is shown

### ISSUE THREAD

**Issue by tcsabina** [daterrell/MMM-ISS#4]
Trying to use this module, but there is no data visible. I can see the frame of the module (Visible, Max height, etc), but no data filled in.

I've checked my (nearest) know location on spotthestation:
https://spotthestation.nasa.gov/widget/widget.cfm?country=Netherlands&region=None&city=Lisse
Which shows (at least at the moment of writing this) some dates.
But using the same Country, Region and City in the module still shows nothing.

Is there a way to debug this module? To see where does this go wrong?

**Comment by daterrell** [comment]
There's a default `minElevation` in the configuration that's set to 40.  If you have sightings in your area that are below that, they're filtered out since you're not likely to see them.  If there aren't any sightings (or they're below `minElevation`), the panel is hidden.

Debugging MM modules isn't that easy, but you can use the browser dev tools (usually F12 on your keyboard) to see network traffic and debug the sources that are in the browser.  Those won't let you debug the node helper that runs on the server side, however.  But, you will see if it has sightings returned when the module asks for data.

**Comment by daterrell** [comment]
Right, I just checked the location you linked, nothing is above 40 degrees.  You could change the `minElevation` to something like 10 or 0 to test it and see if the panel comes up.
