### ISSUE TITLE
Am I doing something wrong - ISS Pass information seems to be way in the future and stuck.

### ISSUE THREAD

**Issue by DdraigX** [daterrell/MMM-ISS#5]
I think I might be doing something wrong?

I've got the module up and works great however it only seems to  display one pass or a pass far off in the future usually at night at 03:00 or something.

Right now the next ISS pass according to gpredict software is 6/28 at 09:16, and the module is displaying 6/29 03:27. Can you give me any insight on what I might be able to look at to give me the next true pass? It frequently loads only 1 for the day and (again at night) and never updates.

**Comment by daterrell** [comment]
Sorry for delay, missed your request.

Make sure you have a correct location by going to [SpotTheStation](https://spotthestation.nasa.gov/sightings/index.cfm), search for and find a location near to you.  According to their documentation, anything within about 50 miles should work.
Look at the Location tag shown to you, e.g. `Location: Boston, Massachusetts, United States`
Use those in your config block appropriately as `city, region, country`.

Yes, it will only show a single viewing time.  It will be the _next_ available viewing time, if there is one that satisfies your `minElevation` configuration value.  Any sighting whose MAX elevation is over your `minElevation` is considered valid, default is 40 (degrees above horizon); time of day is not considered at all, and SpotTheStation is only going to return values at night because you cannot see it during the day with the naked eye.  Sometimes they're 3am, sometimes it's 6pm.

If there aren't any sightings, or no sightings that satisfy `minElevation` in the feed from SpotTheStation the panel is hidden.

Hope that helps.
